# Generated by Django 5.1.15 on 2026-09-29 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('partner_type', models.CharField(choices=[('corporate', 'Corporate'), ('government', 'Government'), ('academic', 'Academic'), ('ngo', 'NGO / Community')], default='corporate', max_length=50)),
                ('logo_url', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('role_title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('trustee', 'Board of Trustees'), ('advisory', 'Advisory Board'), ('staff', 'Core Staff')], default='leadership', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
