# Generated by Django 5.1.15 on 2026-09-29 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.TextField()),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('cover_image_url', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('financial', 'Financial Audit'), ('registration', 'Registration & 12A/80G'), ('csr', 'CSR Document'), ('other', 'Other')], default='policy', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.TextField()),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
